### ISSUE TITLE
Not tracking any app

### ISSUE THREAD

**Issue by matronator** [wakatime/macos-wakatime#208] opened 2024-02-28 03:55 UTC
I downloaded, enabled everything in the Settings, but still I see no Xcode or any other of the tracked apps (they are turned on as to be tracked) in the dashboard. Every other plugin for every other IDE I use works, only this one is not tracking for some reason.

**Comment by alanhamlett** [comment] 2024-02-28 06:01
Xcode should be working but the others not yet.

**Comment by elaninhust** [comment] 2024-02-28 10:07
same issue here, only my Xcode doesn't work. Maybe it works with the M-chip ones

**Comment by alanhamlett** [comment] 2024-02-28 11:51
> same issue here, my Xcode doesn't work either. Maybe it works with the M-chip ones

I've tested on Intel chipset and M-chipset without finding any bugs. Can you build the app by cloning this repo then watch your Xcode console for debug messages and see if it's able to detect when you give Xcode focus, and when you move the cursor inside Xcode?

There was a similar issue we closed where it wasn't working on M1 #118.

**Comment by matronator** [comment] 2024-02-28 12:56
I'm actually on an M2 MacBook Air. Sure, I'll try give it a go after work.

**Comment by matronator** [comment] 2024-03-01 09:56
So I ran the project from Xcode, building it from source and there are no messages indicating when Xcode gets focus. So I guess it doesn't track it properly?

**Comment by alanhamlett** [comment] 2024-03-01 10:51
Does the system tray icon show a warning?
<img width="29" alt="Screenshot 2024-03-01 at 11 42 46 AM" src="https://github.com/wakatime/macos-wakatime/assets/522344/7242eb28-39f3-4576-86d2-60d09db7e808">

When building from source, you need to delete WakaTime from the `Privacy & Security → Accessibility` settings (click the minus button), then click the WakaTime system tray icon and request a11y permission.

Without a11y permission, you should still see the `App changed from...` logs:

```
App changed from nil to Google Chrome (com.google.Chrome)
App changed from Google Chrome to Xcode (com.apple.dt.Xcode)
```

But you won't see file changed logs:
```
Document changed: /git/macos-wakatime/WakaTime/Watcher.swift
```

Do you see the `App changed` logs when switching between different apps?

**Comment by Pia007** [comment] 2024-03-03 01:15
Downloaded a few weeks ago and still have not seen any tracking from Xcode but I do see it when I use vs code. I have:

1. download and installed wakatime for vscodes
2. given the accessibility permission ton wakatime
3. toggled wakatime as a monitored app 

Still cannot see anything. 
Xcode 15.2
M3 chip

**Comment by fstevens30** [comment] 2024-03-04 05:22
I think I have a similar issue. M1 Pro Macbook. Checked wakatime accessibility and reinstalled as well. Log says the following:

```
{"caller":"cmd/run.go:158","func":"cmd.Run","level":"warning","message":"one of the following parameters has to be provided: --config-read, --config-write, --entity, --offline-count, --print-offline-heartbeats, --sync-offline-activity, --today, --today-goal, --useragent, --version","now":"2024-03-04T18:19:36+13:00","os/arch":"darwin/arm64","version":"v1.90.0"}
```

**Comment by alanhamlett** [comment] 2024-03-04 10:25
> Log says the following:
> 
> ```
> one of the following parameters has to be provided...
> ```

@fstevens30 I've released a new version (5.5.3) to prevent that log error, but that log wouldn't prevent tracking your code stats and is probably unrelated to this bug.

@Pia007 @fstevens30 it's really hard/impossible for me to reproduce this bug without an error message. Can you build the app from source and see if you're getting these [expected app logs](https://github.com/wakatime/macos-wakatime/issues/208#issuecomment-1972965669) when changing the currently focused app? Those logs would be inside Xcode after building the app not in the `~/.wakatime/wakatime.log`, but if you see any errors in that log file they're also helpful.

**Comment by alanhamlett** [comment] 2024-03-04 18:47
That must be the bug! It wasn't clearing the monitored apps list in previous releases, but now I can reproduce it on the latest version. I'll get a fix released soon.

**Comment by locke2a** [comment] 2024-03-04 18:52
Alright, I just had a quick look at the code, so I'm not really sure but I think the bug goes back to https://github.com/wakatime/macos-wakatime/commit/3c8d600a29fbc9105c2f3ac814cfea931d1861e7

Seems to me that MonitoredAppsView/buildView(_:) was refactored into another method, but the NSSwitched created inside that new method don't have a tag anymore, so when switchToggled(_:) is called, it changes the state for the app at the index 0, which is currently Arc, hence why it is the only one persisting.

**Comment by alanhamlett** [comment] 2024-03-04 18:59
It was broken with #203, fixed now in #213.

**Closed by alanhamlett** 2024-03-04 18:59 UTC

**Comment by alanhamlett** [comment] 2024-03-04 20:11
I was never able to reproduce it because I already had Xcode enabled, and didn't modify my monitored apps recently.

**Comment by alanhamlett** [comment] 2024-03-04 20:17
Fixed in v5.5.5.

**Comment by elaninhust** [comment] 2024-03-05 03:30
> > same issue here, my Xcode doesn't work either. Maybe it works with the M-chip ones
> 
> I've tested on Intel chipset and M-chipset without finding any bugs. Can you build the app by cloning this repo then watch your Xcode console for debug messages and see if it's able to detect when you give Xcode focus, and when you move the cursor inside Xcode?
> 
> There was a similar issue we closed where it wasn't working on M1 #118.

Sorry for the late. I've built the app and then it works fine. But what's really weird is that when I switch back to the release one (version 5.5.5), it fails again.

Now I am using the one I build locally and everything is fine for now.

**Comment by alanhamlett** [comment] 2024-03-05 06:06
That's good, and make sure to check the monitored apps menu because the bug reset the toggle switches.

**Comment by Pia007** [comment] 2024-03-06 03:40
@alanhamlett Sorry about the late reply. I have built from sourse and here is an image of the logs:

<img width="562" alt="Screenshot 2024-03-05 at 7 37 52 PM" src="https://github.com/wakatime/macos-wakatime/assets/66088725/4b08d0e2-8941-433b-879e-274d6077a2c2">

**Comment by alanhamlett** [comment] 2024-03-06 06:00
@Pia007 does it work with the latest version?

**Comment by Pia007** [comment] 2024-03-06 06:08
> @Pia007 does it work with the latest version?

Yes. It works! I cloned main a few hours ago.

**Comment by alanhamlett** [comment] 2024-03-06 08:16
Awesome! Then you can switch back to using the normal releases so you get updates automatically:
https://github.com/wakatime/macos-wakatime/releases/latest/download/macos-wakatime.zip
